function dgdphi = dgdphi(x,y,ax,ay,bx,by,phi,l)
%DGDPHI
%    DGDPHI = DGDPHI(X,Y,AX,AY,BX,BY,PHI,L)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Oct-2023 16:32:14

t2 = -ay;
t3 = -x;
t4 = (phi.*pi)./1.8e+2;
t5 = cos(t4);
t6 = sin(t4);
t7 = bx.*t5;
t8 = by.*t5;
t9 = bx.*t6;
t10 = by.*t6;
t11 = -t7;
t12 = t2+t8+t9+y;
t13 = ax+t3+t10+t11;
dgdphi = (t12.*((t7.*pi)./1.8e+2-(t10.*pi)./1.8e+2).*2.0+t13.*((t8.*pi)./1.8e+2+(t9.*pi)./1.8e+2).*2.0).*(-l.^2+t12.^2+t13.^2).*2.0;
end
