function dgdx = dgdx(x,y,ax,ay,bx,by,phi,l)
%DGDX
%    DGDX = DGDX(X,Y,AX,AY,BX,BY,PHI,L)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Oct-2023 16:32:37

t2 = (phi.*pi)./1.8e+2;
t3 = cos(t2);
t4 = sin(t2);
dgdx = ((ax-x-bx.*t3+by.*t4).^2+(-ay+y+bx.*t4+by.*t3).^2-l.^2).*(ax.*2.0-x.*2.0-bx.*t3.*2.0+by.*t4.*2.0).*-2.0;
end
