function dgdy = dgdy(x,y,ax,ay,bx,by,phi,l)
%DGDY
%    DGDY = DGDY(X,Y,AX,AY,BX,BY,PHI,L)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Oct-2023 16:32:14

t2 = (phi.*pi)./1.8e+2;
t3 = cos(t2);
t4 = sin(t2);
dgdy = ((ax-x-bx.*t3+by.*t4).^2+(-ay+y+bx.*t4+by.*t3).^2-l.^2).*(ay.*-2.0+y.*2.0+bx.*t4.*2.0+by.*t3.*2.0).*2.0;
end
